### ISSUE TITLE
Error in Online EM ?

### ISSUE THREAD

**Issue by AnnaSaranti** [p2t2/figaro#529] opened 2015-10-30 08:00 UTC
I use the Code of Listing 13.1 Online EM in section 13.2.2 of Avi Pfeffer's Book "Practical Probabilistic Programming" (MEAP V14) with Scala version 2.11.7 and Figaro 3.3.0.0-2.11

    val parameters = ModelParameters() 
    val d = Dirichlet(2.0,2.0,2.0)("d",parameters) 
     class Model(parameters: ParameterCollection, modelUniverse: Universe) 
    { 
        val s = Select(parameters.get("d"), List(1, 2, 3))("s", modelUniverse) 
    }
      
    def f = () => 
    {
        val modelUniverse = new Universe 
        new Model(parameters.priorParameters, modelUniverse) 
        modelUniverse 
    } 
      
    val em = EMWithVE.online(f, parameters) 
    em.start()
    for (i <- 1 to 100) 
    {
        val evidence = List(NamedEvidence("s", Observation(1)))
        em.update(evidence)
    }
    val futureUniverse1 = Universe.createNew() 
    val futureModel1 = new Model(parameters.posteriorParameters, futureUniverse1) 
    println(VariableElimination.probability(futureModel1.s, 1)) 

In the last line I get the following error : 

type mismatch; found : com.cra.figaro.language.Select[Double,List[Int]] with com.cra.figaro.language.HasDensity[List[Int]] required: com.cra.figaro.language.Element[Any] Note: List[Int] <: Any (and com.cra.figaro.language.Select[Double,List[Int]] with com.cra.figaro.language.HasDensity[List[Int]] <: com.cra.figaro.language.Cacheable[List[Int]]), but class Element is invariant in type T. You may wish to define T as +T instead. (SLS 4.5)

Moreover, when replacing that line with this one : 

    println( parameters.posteriorParameters.get("d").asInstanceOf[PrimitiveArray].a.deep.mkString(", ") )

I get 0.3333333333333333, 0.3333333333333333, 0.3333333333333333
as if nothing is learned.

**Comment by bruttenberg** [comment] 2015-10-30 12:29
Hi Anna,

We’ve not tested Figaro with Scala 2.11.7 yet. Although unlikely, it’s still possible that could be the problem. Would you mind trying with Scala 2.11.6?

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by AnnaSaranti** [comment] 2015-10-31 21:23
I've tested it with both 2.11.4 and 2.11.6 and I got again the error message.

    sbt run
    [info] Set current project to Sbt (in build file:/Users/mounara/Documents/workspace/Sbt/)
    [info] Updating {file:/Users/mounara/Documents/workspace/Sbt/}root...
    [info] Resolving org.sonatype.oss#oss-parent;7 ...
    [info] downloading https://jcenter.bintray.com/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar ...
    [info] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.11.6!scala-library.jar (34482ms)
    [info] downloading https://jcenter.bintray.com/org/scala-lang/scala-compiler/2.11.6/scala-compiler-2.11.6.jar ...
    [info] 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.11.6!scala-compiler.jar (125794ms)
    [info] downloading https://jcenter.bintray.com/org/scala-lang/scala-reflect/2.11.6/scala-reflect-2.11.6.jar ...
    [info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.11.6!scala-reflect.jar (38732ms)
    [info] downloading https://jcenter.bintray.com/org/scala-lang/modules/scala-xml_2.11/1.0.3/scala-xml_2.11-1.0.3.jar ...
    [info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-xml_2.11;1.0.3!scala-xml_2.11.jar(bundle) (7272ms)
    [info] downloading https://jcenter.bintray.com/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.3/scala-parser-combinators_2.11-1.0.3.jar ...
    [info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-parser-combinators_2.11;1.0.3!scala-parser-combinators_2.11.jar(bundle) (25309ms)
    [info] downloading https://jcenter.bintray.com/jline/jline/2.12.1/jline-2.12.1.jar ...
    [info] 	[SUCCESSFUL ] jline#jline;2.12.1!jline.jar (9198ms)
    [info] Done updating.
    [info] Compiling 6 Scala sources to *** ...
    [info] 'compiler-interface' not yet compiled for Scala 2.11.6. Compiling...
    [info]   Compilation completed in 50.2 s
    [error] ***.scala:44: type mismatch;
    [error]  found   : com.cra.figaro.language.Select[Double,List[Int]] with com.cra.figaro.language.HasDensity[List[Int]]
    [error]  required: com.cra.figaro.language.Element[Any]
    [error] Note: List[Int] <: Any (and com.cra.figaro.language.Select[Double,List[Int]] with com.cra.figaro.language.HasDensity[List[Int]] <: com.cra.figaro.language.Cacheable[List[Int]]), but class Element is invariant in type T.
    [error] You may wish to define T as +T instead. (SLS 4.5)
    [error]       println(VariableElimination.probability(futureModel1.s, 1)) 
    [error]                                                            ^
    [error] one error found
    [error] (compile:compileIncremental) Compilation failed
    [error] Total time: 309 s, completed Oct 31, 2015 10:13:50 PM

**Comment by bruttenberg** [comment] 2015-11-03 13:09
Thanks Anna. We’ll take a look.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by apfeffer** [comment] 2015-12-09 16:13
Anna,

I’m really sorry for the very slow response. I have tried to recreate your bug, but unfortunately have not been able to do so. It’s very mysterious – why would you have compilation errors when this code compiles successfully for me?

Sorry I couldn’t be more help.

Avi

+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com

**Comment by bruttenberg** [comment] 2015-12-10 13:44
Hi Anna,

We have figured out what the problem is. This line:

val s = Select(parameters.get("d"), List(1, 2, 3))("s", modelUniverse)

Should be changed to one of the following lines:

val s = Select(parameters.get("d"), 1, 2, 3)("s", modelUniverse) OR
val s = Select(parameters.get("d"), List(1, 2, 3)_:*)("s", modelUniverse)

We're still tracking down how this got in there, so thanks for letting us know.

**Comment by AnnaSaranti** [comment] 2015-12-10 14:53
Hi Brian,

yes, it works ! I'm sure you meant :

val s = Select(parameters.get("d"), List(1, 2, 3) :_*)("s", modelUniverse)

Many thanks !
Anna

**Comment by bruttenberg** [comment] 2015-12-10 14:54
Ah, yes, another typo, thanks!

**Comment by apfeffer** [comment] 2015-12-10 14:56
Anna, thanks for pointing out this error. It turns out the version in the code repository was correct but the book had an error. It will be fixed in the final version.

+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com

**Closed** 2016-03-30 18:31 UTC
Labels: book
