### ISSUE TITLE
Open Universe example doesn't work  with new collections library

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#348] opened 2015-01-04 19:21 UTC
It works fine when there are only two choices for the number of samples, but as soon as there are three choices, it takes very few samples.

**Comment by bruttenberg** [comment] 2015-04-16 20:12
Avi, is this still a bug?

**Comment by bruttenberg** [comment] 2015-06-02 20:45
Avi, can you elaborate on this bug? Do you have the code? I'm not sure if this is still a bug or not since I can't reproduce it.

**Comment by apfeffer** [comment] 2015-06-12 16:33
I haven't been able to reproduce the original bug, but I have reproduced the bug Yi reported. As I understand, we're going to create a special pattern for selecting a random element from a collection. Here's the code that reproduces the bug:

import com.cra.figaro.algorithm.sampling._
import com.cra.figaro.language._
import com.cra.figaro.library.atomic.continuous.{ Uniform, Normal }
import com.cra.figaro.library.atomic.discrete.{ Geometric, FromRange }
import com.cra.figaro.library.compound._
import com.cra.figaro.library.collection._
import com.cra.figaro.language.Universe._
import com.cra.figaro.util._

/**
 * An example of open universe reasoning.
 */
object OpenUniverse {
  createNew()

  private def source(): Element[Double] = {
    Uniform(0.0, 1.0)
  }

  private val numSources = FromRange(1,4)

  private val sources = VariableSizeArray(numSources, (i: Int) => source())

  private class Sample {
    val sourceNum = IntSelector(numSources)
    val source = Chain(sourceNum, (i: Int) => sources(i))
    val position = NonCachingChain(source, (x: Double) => Normal(x, 1.0))
  }

  private val sample1 = new Sample
  private val sample2 = new Sample
  private val samples = List(sample1, sample2)
  private val numSamples = samples.length

  private val equal = sample1.source === sample2.source

  def chooseScheme(): ProposalScheme =
    DisjointScheme(
      (0.1, () => ProposalScheme(numSources)),
      (0.9, () => ProposalScheme.default))

  def main(args: Array[String]) = {
    sample1.position.addCondition((y: Double) => y >= 0.7 && y < 0.8)
    sample2.position.addCondition((y: Double) => y >= 0.7 && y < 0.8)
    val alg = MetropolisHastings(chooseScheme, 5000, equal)
    alg.start()
    Thread.sleep(10000)
    alg.stop()
    println(alg.probability(equal, true))
    println(alg.getSampleCount + " samples taken")
    alg.kill
  }
}

**Comment by bruttenberg** [comment] 2015-06-15 15:47
Ok, so I'm going to close this one since the bug you are describing is captured in another issue

**Closed by bruttenberg** 2015-06-15 15:47 UTC
Labels: bug
