### ISSUE TITLE
Repeated factors in variable elimination

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#454] opened 2015-05-11 15:35 UTC
In its inner loop, VE uses a Set[Factor]. This means that if exactly the same factor appears more than once, only one factor will be used. This can lead to incorrect results.

I discovered this in the SFI application to PCFGs. The same factor is produced more than once by different subproblems. With the current VE code, this is causing the factors to be lost.

It should be simple enough to fix this, but before I do, are there any reasons it needs to be a Set?

**Comment by apfeffer** [comment] 2015-05-11 20:25
This can be fixed by making variable elimination use a multiset of factors instead of a set.

However, this causes problems with MakeList. The MakeList implementation relies on variable elimination using a set of factors. The factor creation for a MakeList creates factors for the items in the MakeList. If these items also exist outside the MakeList, their factors will be created twice. When variable elimination used sets, we didn't notice this. But with multisets, these duplicate factors are a problem.

In my opinion, it is incorrect for variable elimination to use a set because repeated factors can legitimately occur, for example, for constraints. So, we have discovered another bug in the MakeList implementation that was hidden by this bug in variable elimination. Since MakeList is deprecated, I suggest moving variable elimination to the multiset implementation. Let's discuss.

I do not believe this is a problem for MakeArray, but I will check.

**Comment by gtakata** [comment] 2015-05-12 11:59
Are these repeated factors truly identical? Ie, do they have the same (identical) parents and children?

What happens when one is modified, eg by summing out, or eliminated?

If they behave differently, even if they have the same structure, then shouldn’t VE treat them as different factors? Maybe the problem is how they are identified to the set function.

On the other hand, what if truly identical factors sneak in, ie they always have identical structure (variables, parents, children) and VE always modifies them identically? Does this introduce a problem, does one need to be eliminated?

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by apfeffer** [comment] 2015-05-12 18:59
Yes, the factors are truly identical – the same variables, structure, and numbers.

When a variable is eliminated, all the factors involving that variable should be multiplied. So if a factor appears twice, it should be squared.

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513

**Comment by gtakata** [comment] 2015-05-13 13:20
I guess I don’t get the use case.

Logically, if two ProblemComponents generate identical factors shouldn’t there be just one in the model and both Components have a reference to it? That way, if the factor is changed, eg by a message from a parent, it only needs to be modified once and both users have access to it. That was kind of the way I was picturing doing SFI, by taking advantage of the redundancy by reusing the factor and its state(s).

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by bruttenberg** [comment] 2015-05-21 19:18
Avi is this fixed and checked in?

**Comment by gtakata** [comment] 2015-05-22 11:25
I haven’t looked at it yet.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by apfeffer** [comment] 2015-05-26 12:34
Yes, it’s fixed and checked in.

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513

**Closed** 2015-06-01 20:20 UTC
Labels: bug
