### ISSUE TITLE
Importance sampling is broken

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#472] opened 2015-06-04 18:22 UTC
Something strange has happened to importance sampling and it no longer works.  Here is an example of a program where it doesn't work. If you replace importance sampling with variable elimination, it works fine.

package chap12

import com.cra.figaro.library.atomic.continuous.Beta
import com.cra.figaro.language.Flip
import com.cra.figaro.library.compound.If
import com.cra.figaro.language.Element
import com.cra.figaro.algorithm.sampling.MetropolisHastings
import com.cra.figaro.language.Universe
import com.cra.figaro.language.Constant
import com.cra.figaro.algorithm.sampling.ProbEvidenceSampler
import com.cra.figaro.algorithm.sampling.ProposalScheme
import com.cra.figaro.language.Select
import com.cra.figaro.algorithm.sampling.Importance
import com.cra.figaro.algorithm.factored.beliefpropagation.ProbEvidenceBeliefPropagation
import com.cra.figaro.algorithm.sampling.OneTimeProbEvidenceSampler
import com.cra.figaro.algorithm.factored.VariableElimination

object BayesianLearningMultipleUniverses {
  class Email(val text: List[String], val label: String)

  // In Chapter 3, the emails were drawn automatically from the training and test sets.
  // They are hardcoded here to keep the example simple.
  val trainingEmail1 = new Email(List("Hello, would you like to receive a free book?"), "spam")
  val trainingEmail2 = new Email(List("Please reply to my question by Tuesday!"), "normal")
  val trainingEmail3 = new Email(List("Hello, I have a question about your book."), "normal")
  val trainingEmails = List(trainingEmail1, trainingEmail2, trainingEmail3)

  // Illustrative list of feature words. In Chapter 3, the feature words were derived from the training emails.
  val featureWords = List("hello", "reply", "question", "free", "book")

  val trainingParameters = Universe.createNew()
  val spamProbability = Beta(2,3)("spam probability", trainingParameters)
  val wordGivenSpamProbabilities =
    for { word <- featureWords }
    yield { Beta(2, 2)(word + " given spam", trainingParameters) }
  val wordGivenNormalProbabilities =
    for { word <- featureWords }
    yield { Beta(2, 2)(word + " given normal", trainingParameters) }
  val allParameters: List[Element[Double]] =
    spamProbability :: wordGivenSpamProbabilities.toList ::: wordGivenNormalProbabilities.toList

  class EmailModel(parameters: Universe) {
    val universe = Universe.createNew()

    val isSpam = Flip(parameters.get[Double]("spam probability"))("is spam", universe)

    val hasWordElements = {
      for { word <- featureWords } yield {
        val givenSpamProbability = parameters.get[Double](word + " given spam")
        val givenNormalProbability = parameters.get[Double](word + " given normal")
        val hasWord = If(isSpam, Flip(givenSpamProbability), Flip(givenNormalProbability))("has " + word, universe)
        (word, hasWord)
      }
    }

    val hasWord = hasWordElements.toMap
  }

  val trainingModels =
    for { email <- trainingEmails } yield {
      val model = new EmailModel(trainingParameters)
      for { word <- featureWords } {
        model.hasWord(word).observe(email.text.contains(word))
        }
      model.isSpam.observe(email.label == "spam")
      model
    }

  val constrainer = Constant(false)("constrainer", trainingParameters)
  def computeLogProbability(model: EmailModel): Double = {
    val alg = new ProbEvidenceSampler(model.universe) with OneTimeProbEvidenceSampler { val numSamples = 100 }
    alg.start()
    val result = alg.logProbEvidence
    alg.kill()
    result
  }
  def constraint(b: Boolean) = {
    trainingModels.foldLeft(0.0)(_ + computeLogProbability(_))
  }
  constrainer.setLogConstraint(constraint)

  def main(args: Array[String]) {
    val learningAlgorithm = MetropolisHastings(ProposalScheme.default(trainingParameters), allParameters:_*)(trainingParameters)
    learningAlgorithm.start()
    Thread.sleep(30000)
    learningAlgorithm.stop()
    val futureEmail = new Email(List("Feel free to reply if you have any ideas."), "unknown")
for { param <- allParameters } {
  println(param.name.string + ": " + learningAlgorithm.mean(param))
}
    val reasoningParameters = Universe.createNew()
    val learnedSpamProbabilities =
      learningAlgorithm.distribution(trainingParameters.getElementByReference("spam probability")).toList
println("learnedSpamProbabilities = " + learnedSpamProbabilities)
    Select(learnedSpamProbabilities:_*)("spam probability", reasoningParameters)
    for { word <- featureWords } {
      val learnedGivenSpamProbability =
        learningAlgorithm.distribution(trainingParameters.getElementByReference(word + " given spam")).toList
      val learnedGivenNormalProbability =
        learningAlgorithm.distribution(trainingParameters.getElementByReference(word + " given normal")).toList
      Select(learnedGivenSpamProbability:_*)(word + " given spam", reasoningParameters)
      Select(learnedGivenNormalProbability:_*)(word + " given normal", reasoningParameters)
    }
    learningAlgorithm.kill()

    val futureModel = new EmailModel(reasoningParameters)

    for { word <- featureWords } {
      futureModel.hasWord(word).observe(futureEmail.text.contains(word))
    }
    val futureAlgorithm = Importance(futureModel.isSpam)(futureModel.universe)
    futureAlgorithm.start()
    println("Probability new email is spam = " + futureAlgorithm.probability(futureModel.isSpam, true))
    futureAlgorithm.kill()
  }

}

**Comment by apfeffer** [comment] 2015-06-04 18:24
Sorry, I was missing the Thread.sleep in there (cut and paste error). I've tried it with both one-time importance and anytime importance with a reasonable time. Doesn't work.

**Comment by bruttenberg** [comment] 2015-06-04 23:49
Avi, Importance sampling is working as intended. In the model you provided, futureModel.isSpam is compound Flip that depends upon parameters.get[Double]("spam probability"). The parameter universe you pass in is called reasoningParameters, which has an element Select(learnedSpamProbabilities: _*)("spam probability", reasoningParameters) declared on it. But you are running Importance sampling the universe of futureModel, which is a different universe than the parameters. In Importance sampling, elements that are not on the universe of the algorithm are ignored. Since the reasoningParameters universe never has it's elements initialized, their values are null and hence you try to sampled the compound Flip with a null valued parent.

**Comment by apfeffer** [comment] 2015-06-05 11:39
This is bad behavior. Importance sampling should use the current values of elements outside the sampling universe. Otherwise you can’t use importance sampling with multiple universes, which is a natural use case.

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513

**Comment by bruttenberg** [comment] 2015-06-05 12:02
It does use the current values of elements outside the universe, but the current values are null since the element is never initialized. I will close this as not a bug.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Closed** 2015-06-05 12:26 UTC
