### ISSUE TITLE
MPEVariableElimination gives incorrect answer

### ISSUE THREAD

**Issue by mhoward2718** [p2t2/figaro#554] opened 2016-03-10 15:04 UTC
The following program will report 1 as the most likely value, when it should be 0.

```scala
  def is4(i: Int) = i == 4

  def main(args: Array[String]) {
    val rolls = for { i <- 1 to 2 } yield Uniform(1,2,3,4)("r" + i.toString(), Universe.universe)
    val c = Container(rolls: _*)
    val num4 = c.count(is4)
    val algorithm = MPEVariableElimination()
    algorithm.start()
    println("Most likely number of '4's : " + algorithm.mostLikelyValue(num4))
    algorithm.stop()
    algorithm.kill()
  }
```

Here is the output in debug mode:
```
Elements appearing in factors and their ranges:
2(r2@2): Uniform(1, 2, 3, 4): Regular(1),Regular(2),Regular(3),Regular(4)
5(r1@1): Uniform(1, 2, 3, 4): Regular(1),Regular(2),Regular(3),Regular(4)
8(@3): com.cra.figaro.library.compound.FoldLeft@3: Regular(0),Regular(1),Regular(2)
*****************
Starting factors

|------------|------|
|     2      |      |
|------------|------|
| Regular(1) | 1.0  |
| Regular(2) | 1.0  |
| Regular(3) | 1.0  |
| Regular(4) | 1.0  |
|------------|------|

|------------|------|
|     5      |      |
|------------|------|
| Regular(1) | 1.0  |
| Regular(2) | 1.0  |
| Regular(3) | 1.0  |
| Regular(4) | 1.0  |
|------------|------|

|------------|------------|------------|------|
|     10     |     5      |     11     |      |
|------------|------------|------------|------|
| Regular(0) | Regular(1) | Regular(0) | 1.0  |
| Regular(0) | Regular(2) | Regular(0) | 1.0  |
| Regular(0) | Regular(3) | Regular(0) | 1.0  |
| Regular(0) | Regular(4) | Regular(1) | 1.0  |
|------------|------------|------------|------|

|------------|------------|------------|------|
|     11     |     2      |     8      |      |
|------------|------------|------------|------|
| Regular(1) | Regular(1) | Regular(1) | 1.0  |
| Regular(0) | Regular(4) | Regular(1) | 1.0  |
| Regular(0) | Regular(1) | Regular(0) | 1.0  |
| Regular(0) | Regular(2) | Regular(0) | 1.0  |
| Regular(1) | Regular(4) | Regular(2) | 1.0  |
| Regular(0) | Regular(3) | Regular(0) | 1.0  |
| Regular(1) | Regular(2) | Regular(1) | 1.0  |
| Regular(1) | Regular(3) | Regular(1) | 1.0  |
|------------|------------|------------|------|

***************** Eliminition Score: 0.0
*****************
Eliminating 2
Input factors:
|------------|------------|------------|------|
|     11     |     2      |     8      |      |
|------------|------------|------------|------|
| Regular(1) | Regular(1) | Regular(1) | 1.0  |
| Regular(0) | Regular(4) | Regular(1) | 1.0  |
| Regular(0) | Regular(1) | Regular(0) | 1.0  |
| Regular(0) | Regular(2) | Regular(0) | 1.0  |
| Regular(1) | Regular(4) | Regular(2) | 1.0  |
| Regular(0) | Regular(3) | Regular(0) | 1.0  |
| Regular(1) | Regular(2) | Regular(1) | 1.0  |
| Regular(1) | Regular(3) | Regular(1) | 1.0  |
|------------|------------|------------|------|

|------------|------|
|     2      |      |
|------------|------|
| Regular(1) | 1.0  |
| Regular(2) | 1.0  |
| Regular(3) | 1.0  |
| Regular(4) | 1.0  |
|------------|------|

Result factor
|------------|------------|------|
|     11     |     8      |      |
|------------|------------|------|
| Regular(0) | Regular(1) | 1.0  |
| Regular(0) | Regular(0) | 1.0  |
| Regular(1) | Regular(2) | 1.0  |
| Regular(1) | Regular(1) | 1.0  |
|------------|------------|------|

*****************
Eliminating 8
Input factors:
|------------|------------|------|
|     11     |     8      |      |
|------------|------------|------|
| Regular(0) | Regular(1) | 1.0  |
| Regular(0) | Regular(0) | 1.0  |
| Regular(1) | Regular(2) | 1.0  |
| Regular(1) | Regular(1) | 1.0  |
|------------|------------|------|

Result factor
|------------|------|
|     11     |      |
|------------|------|
| Regular(0) | 1.0  |
| Regular(1) | 1.0  |
|------------|------|

*****************
Eliminating 5
Input factors:
|------------|------------|------------|------|
|     10     |     5      |     11     |      |
|------------|------------|------------|------|
| Regular(0) | Regular(1) | Regular(0) | 1.0  |
| Regular(0) | Regular(2) | Regular(0) | 1.0  |
| Regular(0) | Regular(3) | Regular(0) | 1.0  |
| Regular(0) | Regular(4) | Regular(1) | 1.0  |
|------------|------------|------------|------|

|------------|------|
|     5      |      |
|------------|------|
| Regular(1) | 1.0  |
| Regular(2) | 1.0  |
| Regular(3) | 1.0  |
| Regular(4) | 1.0  |
|------------|------|

Result factor
|------------|------------|------|
|     10     |     11     |      |
|------------|------------|------|
| Regular(0) | Regular(0) | 1.0  |
| Regular(0) | Regular(1) | 1.0  |
|------------|------------|------|

*****************
Eliminating 11
Input factors:
|------------|------------|------|
|     10     |     11     |      |
|------------|------------|------|
| Regular(0) | Regular(0) | 1.0  |
| Regular(0) | Regular(1) | 1.0  |
|------------|------------|------|

|------------|------|
|     11     |      |
|------------|------|
| Regular(0) | 1.0  |
| Regular(1) | 1.0  |
|------------|------|

Result factor
|------------|------|
|     10     |      |
|------------|------|
| Regular(0) | 1.0  |
|------------|------|

*****************
Eliminating 10
Input factors:
|------------|------|
|     10     |      |
|------------|------|
| Regular(0) | 1.0  |
|------------|------|

Result factor
|------|
|      |
|------|
| 1.0  |
|------|

*****************
|------|
|      |
|------|
| 1.0  |
|------|

Most likely number of '4's : 1
```

**Comment by apfeffer** [comment] 2016-03-10 16:12
I have an inkling what the problem is. MPE is finding the most likely joint assignment to all the variables. In other words, this is the assignment to *all* the variables that has the highest probability. In this example, the variables are:

-          The roll of the first die

-          The roll of the second die

-          The number of 4s

All assignments to these three variables such that the number of 4s is consistent with the rolls of the two dice are equally likely. In the presence of ties, MPE VE chooses arbitrarily. So any of the three possible answers for number of 4s could be correct.

What we really want here, and what we think of intuitively when we ask for the most likely number of 4s, is the marginal MAP.

So I think this is not a bug. Do you all concur?

+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com

**Comment by bruttenberg** [comment] 2016-03-12 00:01
That makes sense. It’s basically just because of the uniform priors that all outcomes are equally likely. Let’s close this and release.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Closed** 2016-03-14 19:51 UTC
