### ISSUE TITLE
MultiDecision Example throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mreposa** [p2t2/figaro#391] opened 2015-03-05 15:18 UTC
Running MultiDecision
01:51 PM
java.lang.IndexOutOfBoundsException: 1
        at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:51)
        at scala.collection.immutable.List.apply(List.scala:83)
        at com.cra.figaro.algorithm.factored.ProbQueryVariableElimination$$anonfun$12.apply(VariableElimination.scala:257)
        at com.cra.figaro.algorithm.factored.ProbQueryVariableElimination$$anonfun$12.apply(VariableElimination.scala:257)
        at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
        at scala.collection.Iterator$class.foreach(Iterator.scala:743)
        at com.cra.figaro.algorithm.factored.factors.Indices$$anon$1.foreach(Factor.scala:182)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at com.cra.figaro.algorithm.factored.factors.Indices.foreach(Factor.scala:178)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
        at com.cra.figaro.algorithm.factored.factors.Indices.filter(Factor.scala:178)
        at com.cra.figaro.algorithm.factored.ProbQueryVariableElimination.computeDistribution(VariableElimination.scala:257)
        at com.cra.figaro.algorithm.factored.ProbQueryVariableElimination.computeExpectation(VariableElimination.scala:267)
        at com.cra.figaro.example.MultiDecision$.main(MultiDecision.scala:75)
        at com.cra.figaro.example.MultiDecision.main(MultiDecision.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:68)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:99)
        at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:68)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:99)
        at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
        at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
        at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
01:51 PM

**Comment by bruttenberg** [comment] 2015-03-13 13:25
This is tricky and maybe not a bug. It occurs because we query for the expectation of a variable after we have run multiple algorithms. Because our factored algorithms now wipe out a lot of previous factors/variables, when we call expectation after running many algorithms the Variables are out of sync. This can be solved by moving the expectation query before running other algorithms, but not sure if  this should be fixed in the code

**Closed** 2015-03-31 20:05 UTC
Labels: bug
